# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FitGAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PoseEngine', :path => '../PoseEngine'

  pod 'Alamofire'
  pod 'BMPlayer'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'GoogleSignIn'
  pod 'GoogleMLKit/PoseDetection'
  pod 'GoogleMLKit/PoseDetectionAccurate'
  pod 'KakaoSDK'
  pod 'Kingfisher'
  pod 'lottie-ios'
  pod 'Moya/RxSwift'
  pod 'naveridlogin-sdk-ios'
  pod 'PNChart'
  pod 'PMSuperButton'
  pod 'R.swift'
  pod 'RAMAnimatedTabBarController'
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Then'
  pod 'Toast-Swift'
end
